### ISSUE TITLE
Get Data from the Internet

### ISSUE THREAD

**Issue by zonghan-kim** [google-developer-training/basic-android-kotlin-compose-training-mars-photos#11]
**URL of codelab:**

**Specify the language of the codelab if it is not English:**

**In which task and step of the codelab can this issue be found?**
[8. Parsing JSON response using kotlinx.serialization](https://developer.android.com/codelabs/basic-android-kotlin-compose-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-5-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-getting-data-internet#7)

**Describe the problem**
private val retrofit = Retrofit.Builder()
    .addConverterFactory(Json.asConverterFactory("application/json".toMediaType()))
    .baseUrl(BASE_URL)
    .build()

The toMediaType() is not available.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_
_API version of the emulator:_

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
private val retrofit = Retrofit.Builder()
    .addConverterFactory(Json.asConverterFactory(MediaType.get("application/json")))
    .baseUrl(BASE_URL)
    .build()

MediaType.get() resolves the issue.toMediaType() Nothing can be solved.

**Comment by osuleymanova** [comment]
Hello @zonghan-kim,

Thank you for reaching out to us and reporting this issue. The code block is updated:

![Screenshot 2023-01-04 at 8 46 32 AM](https://user-images.githubusercontent.com/86437155/210607813-f21d7453-113f-4eee-9619-f41776cec7ff.png)
