### ISSUE TITLE
Get Data from the Internet

### ISSUE THREAD

**Issue by casanovaP** [google-developer-training/basic-android-kotlin-compose-training-mars-photos#12]
**URL of codelab:**
https://developer.android.com/codelabs/basic-android-kotlin-compose-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-5-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-getting-data-internet#7

**Specify the language of the codelab if it is not English:**

**In which task and step of the codelab can this issue be found?**
Step 8
Update MarsApiService and MarsViewModel

**Describe the problem**
a dependency is missing for the .toMediaType() function
implementation "com.squareup.okhttp3:okhttp:4.7.2"
without it you cannot perform the import and therefore get an error in the .toMediaType()
please add the dependency to the course, i had to look it up

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_
_API version of the emulator:_

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hello @casanovaP,

Thank you for reaching out to us and reporting this issue. The code block is updated:

![Screenshot 2023-01-04 at 8 46 32 AM](https://user-images.githubusercontent.com/86437155/210608100-3a754762-db64-4041-869a-74bc023deac2.png)
