### ISSUE TITLE
Get Data from the Internet

### ISSUE THREAD

**Issue by MasiarNovine** [google-developer-training/basic-android-kotlin-compose-training-mars-photos#14]
**URL of codelab:**

[Get data from the internet](https://developer.android.com/codelabs/basic-android-kotlin-compose-getting-data-internet?hl=en)

**In which task and step of the codelab can this issue be found?**

In [Parse the JSON response with kotlinx.serialization](https://developer.android.com/codelabs/basic-android-kotlin-compose-getting-data-internet?hl=en#7) under *Update MarsApiService and MarsViewModel*.

**Describe the problem**

* The method `toMediaType()` of the class `MediaType` is unknown, when using `import okhttp3.MediaType` as written in the code snippet.
* For newer versions of *OkHttp* the method is contained in a `Companion` of the class `MediaType`.

**Steps to reproduce?**

1. Go to the second code snippet under *Update MarsApiService and MarsViewModel*.
2. Try to initialize the variable `retrofit`: The method `toMediaType()` used for conversion of the string value is not known, when using the given import statement.

**Possible solution**

Change the import statement in the code snippet of the codelab to `import okhttp3.Companion.toMediaType` and update the modules `build.gradle` with a newer version of *OkHttp*, e.g. by including `implementation "com.squareup.okhttp3:okhttp:4.10.0"`.

**Versions**

* Android Studio Dolphin 2021.3.1 Patch 1
* Android 7.0 (x86)

**Comment by MasiarNovine** [comment]
Duplicate of #10 and others, but might still be useful due to the possible solution given.

**Comment by osuleymanova** [comment]
Hello @MasiarNovine,

Thank you for reaching out to us and reporting this issue. The code block is updated:

![Screenshot 2023-01-04 at 8 46 32 AM](https://user-images.githubusercontent.com/86437155/210607959-b61433bc-cc49-4213-ba27-eea1026d518a.png)
