### ISSUE TITLE
What is AmphibiansViewModel.Factory?

### ISSUE THREAD

**Issue by malshoff** [google-developer-training/basic-android-kotlin-compose-training-mars-photos#18]
**URL of codelab:**

https://developer.android.com/codelabs/basic-android-kotlin-compose-add-repository?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-5-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-repository#5

**Specify the language of the codelab if it is not English:**

**In which task and step of the codelab can this issue be found?**
Task 6, Step 4

**Describe the problem**
Typo, AmphibiansViewModel isn't a thing.

**Steps to reproduce?**
Check link

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
<img width="872" alt="Screen Shot 2022-11-26 at 12 51 21 PM" src="https://user-images.githubusercontent.com/3699324/204108429-353f06df-e903-4e4e-afb7-e64fb0f29b86.png">

**Comment by osuleymanova** [comment]
Hello @malshoff,

Thank you so much for reaching out to us and reporting this issue. The typo is fixed:

![Screen Shot 2022-11-28 at 2 21 34 PM](https://user-images.githubusercontent.com/86437155/204393721-2e8f32ac-bdfc-46f6-ad75-1395a4cecd4e.png)
