### ISSUE TITLE
Get Data from the Internet

### ISSUE THREAD

**Issue by folsze** [google-developer-training/basic-android-kotlin-compose-training-mars-photos#21]
Subsection Number 8:
    .addConverterFactory(Json.asConverterFactory("application/json".toMediaType()))

marked as red because:

https://stackoverflow.com/questions/57358023/okhttp3-in-kotlin-string-mediatype-does-not-work

So the 2020 answer from Stackoverflow is missing as a task, before the said task

**Comment by osuleymanova** [comment]
Hello @folsze,

Thank you for reaching out to us and sharing your feedback. The code block is updated, it should be .addConverterFactory(Json.asConverterFactory(MediaType.get("application/json"))):

![Screenshot 2023-01-04 at 8 46 32 AM](https://user-images.githubusercontent.com/86437155/210608556-f894ca38-a80e-4981-bf71-a8a9fc3ddbe0.png)
