### ISSUE TITLE
Get Data from the Internet

### ISSUE THREAD

**Issue by josephjebin** [google-developer-training/basic-android-kotlin-compose-training-mars-photos#22]
**URL of codelab:**
https://developer.android.com/codelabs/basic-android-kotlin-compose-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-5-pathway-1%3Fauthuser%3D2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-getting-data-internet&authuser=2#7 

**Specify the language of the codelab if it is not English:**

**In which task and step of the codelab can this issue be found?**
8. Parse the JSON response with kotlinx.serialization -> Update MarsApiService and MarsViewModel -> Step 4

**Describe the problem**
Code block is outdated. 
    .addConverterFactory(Json.asConverterFactory("application/json".toMediaType()))
should be 
    .addConverterFactory(Json.asConverterFactory(MediaType.get("application/json")))

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ Dolphin 
_API version of the emulator:_

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hello @josephjebin,

Thank you for reaching out to us and reporting this issue. The code block is updated:

![Screenshot 2023-01-04 at 8 46 32 AM](https://user-images.githubusercontent.com/86437155/210606561-ba970903-b8d6-4cbb-96dd-9818183473c6.png)
