### ISSUE TITLE
Load and Display Images from the Internet

### ISSUE THREAD

**Issue by hassan0599** [google-developer-training/basic-android-kotlin-compose-training-mars-photos#30]
**URL of codelab:**
https://developer.android.com/codelabs/basic-android-kotlin-compose-load-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-5-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-load-images#1

**In which task and step of the codelab can this issue be found?**
Task 2 (App Overview)

**Describe the problem**
The paragraph should read:
"Your app will also handle network errors gracefully by displaying an error message."
instead of:
"Your app will also handles network errors gracefully by displaying an error message."

**Comment by osuleymanova** [comment]
Hello @hassan0599,

Thank you for reaching out to us. The typo is fixed and will be published soon.
